### ISSUE TITLE
libpython error during installation

### ISSUE THREAD

**Issue by sibyjackgrove** [jlapeyre/diffeq_julia#1]
@jlapeyre Thank you for this package. I just installed it following the instructions. But I am getting the following error when I do `import  diffeq_julia`

```
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
ERROR: InitError: Incompatible `libpython` detected.
`libpython` for C:\Users\splathottam\.conda\envs\diffeq_julia\python.exe is:
    C:\Users\splathottam\.conda\envs\diffeq_julia\python37.dll
`libpython` for C:\Users\splathottam\.conda\envs\pvder\python.exe is:
    C:\Users\splathottam\.conda\envs\pvder\python37.dll
PyCall.jl only supports loading Python environment using
the same `libpython`.
```

I am installing this in the `diffeq_julia ` Conda environment. But for some reason, the `libpython`  in another Conda environment is getting picked up. Could you suggest a fix?

**Comment by jlapeyre** [comment]
> I am installing this in the diffeq_julia Conda environment.

I don't know which environment this is. Did you just create it ?
I developed these things without using Conda at all.

Something like this should work.

* Clone this repo

* `python -m venv ./venv`
*  `source ./venv/bin/activate`
* `pip install -r requirements.txt`
* `pip install -e .`
*  `pip install ipython`
* Start ipython and do `import diffeq_julia`

I have see something about the error you mention, in PyCall or pyjulia. I'll look into it.

**Comment by sibyjackgrove** [comment]
@jlapeyre Yes, diffeq_julia is just a Python 3.7 environment I created using Conda. I generally use conda to create virtual environments. But I will try the method you showed.

**Comment by jlapeyre** [comment]
I think the solution may involve setting this environment variable `PYCALL_JL_RUNTIME_PYTHON` in the right place.
This should be set to what you get from `which python`.
You might try setting that environment variable before launching python.

**Comment by jlapeyre** [comment]
@sibyjackgrove . I just push a commit to julia_project that sets the above environment variable early. I wonder if this solves your original issue. It would be nice if this supports both conda and venv.

**Comment by jlapeyre** [comment]
I should point out that julia_project should does *not* require installing the package diffeq_julia in dev mode, i.e. with `-e .`.
You can also install it in the normal way.

For example, you can download `diffeq_julia`, then make an environment variable on the same level, not under it.
*  `git clone https://github.com/jlapeyre/diffeq_julia`
*  `mkdir diffeq_env`
*  `cd diffeq_env`
*  `python -m venv ./venv`
* `source ./venv/bin/activate`
* `pip install -r ../diffeq_julia/requirements.txt`
* `pip install ../diffeq_julia`

I should try to get this to work via conda as well.

**Comment by jlapeyre** [comment]
>  just push a commit to julia_project that sets the above environment variable early.
I have a feeling this won't work. I am setting it on the Python side, and it might be too late for Julia to see it.... Trying something else.

**Comment by sibyjackgrove** [comment]
@jlapeyre Yes, I reinstalled `julia_project ` after pulling the latest commit. However, I am getting the same error when I do diffeq_julia.compile_diffeq_julia(). It is setting the PYCALL_JL_RUNTIME_PYTHON  to the correct Python path for the environment. But as you said, Julia doesn't seem to be seeing it.

**Comment by jlapeyre** [comment]
Arg! I pushed a commit, then a change, then reverted with a new commit.
I fear that you got the bad commit in the middle. Can you try again, please. Sorry!

**Comment by jlapeyre** [comment]
>  I am getting the same error when I do diffeq_julia.compile_diffeq_julia(). 

Oh, wait. I did not know that this is happening when you are compiling. This is late in the process.

But, you apparently have no problem importing `diffeq_julia` to begin? It is only when compiling that you get the error ?

**Comment by jlapeyre** [comment]
I see what may be an important difference with `python -m venv`, no libpython is copied into your virtual environment. The libpython that created the venv (e.g. from your system installation) is still used. So different envs might use the same libpython. But, Conda seems to make a copy of libpython for each virtual env.

**Comment by jlapeyre** [comment]
`PyCall` insists that users rebuild PyCall to use it with a different library.  Even if it is a bit for bit copy in a different location. I can look for a way around this, but won't be able to get to it this week.

Using `venv`, has a smaller proliferation of paths to libpython is a workarund.

**Comment by jlapeyre** [comment]
Here is an issue for this:
https://github.com/jlapeyre/julia_project/issues/2

PyCall.jl  README says flatly that conda virtual environments are not supported:

https://github.com/JuliaPy/PyCall.jl#python-virtual-environments

It doesn't say why, but guess it's because the libpython is always copied to an environment.

**Comment by sibyjackgrove** [comment]
@jlapeyre Thank you for looking into this further. So, from what I understand it won't work with Conda environments at this time?

**Comment by jlapeyre** [comment]
Yes. My best understanding is julia_project and diffeq_julia will not work with Conda environments because they are not supported by the underlying tool, PyCall.  They are supported by venv.

We may be able to find a way to support Conda environments. But, that will take some work.

**Comment by jlapeyre** [comment]
@sibyjackgrove But, it would be very useful to me to know if it works for you with venv on Windows. I have only tested on linux.

**Comment by sibyjackgrove** [comment]
@jlapeyre I pulled the latest commits and tried using venv on Windows 10. But getting the following error when I do  `import diffeq_julia:`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Box Sync\GitHub\diffeq_julia\diffeq_julia\__init__.py", line 1, in <module>
    from ._julia_project import julia, compile_diffeq_julia, update_diffeq_julia
  File "C:\Users\Box Sync\GitHub\diffeq_julia\diffeq_julia\_julia_project.py", line 18, in <module>
    julia_project.run()
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia_project\_julia_project.py", line 75, in run
    self.diagnostics_after_init()
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia_project\_julia_project.py", line 284, in diagnostics_after_init
    from julia import Main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia\core.py", line 247, in load_module
    JuliaMainModule(self, fullname))
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia\core.py", line 149, in __init__
    self._julia = loader.julia
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia\core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia\core.py", line 513, in __init__
    self._call("const PyCall = Base.require({0})".format(PYCALL_PKGID))
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia\core.py", line 549, in _call
    self.check_exception(src)
  File "C:\Users\Box Sync\python_envs\venv\lib\site-packages\julia\core.py", line 603, in check_exception
    raise JuliaError(u'Exception \'{}\' occurred while calling julia code:\n{}'
julia.core.JuliaError: Exception 'InitError' occurred while calling julia code:
const PyCall = Base.require(Base.PkgId(Base.UUID("438e738f-606a-5dbb-bf0a-cddfbfd45ab0"), "PyCall"))
```

**Comment by jlapeyre** [comment]
EDIT: I found the problem, see three comments down.

Thanks for the report. I can't get to this till next week.

**Comment by jlapeyre** [comment]
It looks like `PyCall` is not being found. I saw something like this before, but I can't recall what caused it.

Can you post the contents of `diffeq_julia.log`?

I also pushed another commit that adds a bit more debug logging.

**Comment by jlapeyre** [comment]
I pushed commits to `diffeq_julia` adding a missing file that copies necessary files during install. Before it would only work in development mode. This fixes a bug that has nothing to do with the error reported in your most recent log above.

**Comment by jlapeyre** [comment]
EDIT: The problem is that `PyCall` was built with the python (really libpython) in a conda environment. But, you are now trying to use it in venv virtual environment. (And previously, you were using PyCall from a "diffeq_julia" conda environment which also has a different libpython from the one you used used to build PyCall)

This is a limitation of `PyCall.jl`. Try `import julia` when in your virtual environment. It should give you a similar error and tell you how to fix it. I have also pushed a commit to `julia_project`, which `diffeq_julia` depends on, so that it will now give you the same error message.

This is an *enormous* limitation of `PyCall` (and of pyjulia, since it relies on PyCall).

Actually, when I test this on my system, the libpythons are the really the same, or at least compatible. So PyCall *could* let you proceed and all would work fine. But, it won't let you. It is too conservative.

The following is not wrong, but it's imprecise.
~You might try removing `PyCall`. I think there may some conflict from having used it with conda. At least try removing the `.ji` files in `.julia/compiled/v1.7/PyCall/` (whatever this is called in Windows). Maybe even remove the directory `.julia/packages/PyCall/`.~

**Comment by jlapeyre** [comment]
I pushed a new version of the package `julia_project` that `diffeq_julia` depends on. It detects the libpython conflict and offers to perform a couple of solutions.

**Comment by sibyjackgrove** [comment]
@jlapeyre Thank you for the updates! I was able to get it working on Windows with `venv` environment. When I did `diffeq_julia.compile_diffeq_julia(`) I got the prompt that detected the `libpython `conflicts and offered solutions. I selected the 2nd solution.
Unfortunately, it still doesn't work with my `conda `environment due to the Incompatible `libpython` error. Due to some strange reason, the  `libpython` is pointing to the Python in another `conda `environment.

**Comment by jlapeyre** [comment]
Thanks for trying again.

> When I did `diffeq_julia.compile_diffeq_julia()` I got the prompt that detected the libpython conflicts and offered solutions.

The check for the conflict does not happen when you call `diffeq_julia.compile_diffeq_julia()`. It happens every time you do `import diffeq_julia` in a fresh session. Are you sure about when you saw the message and chose the solution? But, in any case, it seems it did not work for you.

Can you check to see if the folder `diffeq_julia/depot/` (or `diffeq_julia\depot\` I suppose on Windows) was indeed created?

 I don't have access to a Windows machine at the moment, but I read that the standard location for the Julia "depot" is `C:\Users\user\.julia`. A folder with the same files should be created as `diffeq_julia\depot\`. In particular, a version of `PyCall` should be built there that is compiled with the current libpython (from your venv). And an environment variable is set so that this location for the depot is used and `C:\Users\user\.julia` is ignored. But, it sounds like the old `PyCall` in C:\Users\user\.julia` is being used anyway.

**Comment by sibyjackgrove** [comment]
> Can you check to see if the folder `diffeq_julia/depot/` (or `diffeq_julia\depot\` I suppose on Windows) was indeed created?

Yes, `diffeq_julia/depot/' was created within my cloned diffeq_julia repository.

> I don't have access to a Windows machine at the moment, but I read that the standard location for the Julia "depot" is C:\Users\user\.julia. A folder with the same files should be created as diffeq_julia\depot\. In particular, a version of PyCall should be built there that is compiled with the current libpython (from your venv). And an environment variable is set so that this location for the depot is used and C:\Users\user\.julia is ignored. But, it sounds like the old PyCall in C:\Users\user.julia` is being used anyway.

Yes, I checked `C:\Users\.julia `and found that it has exactly the same folders as `diffeq_julia\depot\.`

**Comment by jlapeyre** [comment]
That message about the conflict was probably in error. EDIT:  I mean, if no PyCall has been built, then the pyjulia reports a conflicting library. I have since modified `julia_project` to detect this.

I have pushed more fixes to `julia_project`, on which `diffeq_julia` depends.  Can you try to install the latest `julia_project` ?

In any case, once `diffeq_julia\depot\` is present and populated, it should be detected and used without any conflicts. As long as you are using the same python that you used to build and populate `diffeq_julia\depot\`

**Comment by sibyjackgrove** [comment]
> I have pushed more fixes to `julia_project`, on which `diffeq_julia` depends. Can you try to install the latest `julia_project` ?

I pulled the latest commits and installed it again. It seems to work fine when I do import diffeq_julia. However, compiling the Julia system image and creating the depot takes a long time.

**Comment by jlapeyre** [comment]
Good to hear that it works! I just tested on linux: `import diffeq_julia` takes 6.5 minutes. Exiting and doing it again then takes 1.7s. I have heard that some of these things take much longer on Windows. Do you find that it is much slower ?

The 6.5 minutes includes everything except installing Julia; i.e. downloading registries etc.

I made some effort to ask all questions at once. That is, you don't get a question, then 4 minutes of waiting, then another question. In other words, I want to make this as painless and automatic as possible.

**Comment by sibyjackgrove** [comment]
It is taking around 10 s to do `import diffeq_julia` after the first import. Also, it takes around 45 s to do `from diffeq_julia import ode`. But my system is pretty slow as well, so that could be one reason.

Anyway, I'll pull the latest commits and do another installation.

**Comment by sibyjackgrove** [comment]
@jlapeyre I was trying to install julia_project after pulling the latest commits. But I am getting the following error.

```
(venv) C:\GitHub\julia_project>pip install .
Processing c:\users\splathottam\box sync\github\julia_project
Requirement already satisfied: julia in c:\users\splathottam\box sync\python_envs\venv\lib\site-packages (from julia-project==0.0.19) (0.5.7)
Collecting find_julia@ git+https://github.com/jlapeyre/find_julia.git
  Cloning https://github.com/jlapeyre/find_julia.git to c:\users\splathottam\appdata\local\temp\pip-install-pferopok\find-julia
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/jlapeyre/find_julia.git 'C:\Users\splathottam\AppData\Local\Temp\pip-install-pferopok\find-julia'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

I think it's because I don't have git available on the Windows command line. I only have Git available through Git Bash.

**Comment by jlapeyre** [comment]
Arg. That's a problem that wasn't mentioned when I looked up how to do that online. I just looked for similar problems. But, it seems that some people *are* able to use this syntax with gitbash. For example:

Here gitbash works apparantly. The failure is unrelated.
https://stackoverflow.com/questions/64453269/how-do-i-install-this-github-package-via-git-bash-amazon-crawler

Here is another case of someone using gitbash with this syntax:
https://stackoverflow.com/questions/53528553/cannot-install-python-package-in-git-bash

I never heard of gitbash till just now, so I don't have a good idea of what to do.

Also, you can try installing find_julia by downloading and doing pip install. I think the installation of julia_project then probably won't try to use git to reinstall it.

I'll register find_julia and julia_project with pypi, which should take care of this. But, still, there should be a way for you to use setup.py that has these kinds of entries.

**Comment by jlapeyre** [comment]
@sibyjackgrove  I uploaded find_julia and julia_project to pypi. I updated diffeq_julia to use these. So there should be no more problems with getting things from github.

I also have opened a PR to diffeqpy including what is is diffeq_julia. I'll make changes there from now on.

**Comment by sibyjackgrove** [comment]
@jlapeyre Thanks for the updates. I have pulled it and reinstalled  `julia_project `and `diffeq_julia`. The installation completed without any error!

**Comment by jlapeyre** [comment]
For completeness, here is the PR to diffeqpy:

https://github.com/SciML/diffeqpy/pull/100
